### PR TITLE
#637 incompatible with IDEA 2020.3

### PR DESCRIPTION
**Pull request by BorzdeG**
1. Upgraded Gradle wrapper & plugins
2. Fixed support IDEA 2020.3

### CODE REVIEW

**Comment by Kurre** [comment]
Works with Webstorm 2020.3 EAP.

However, building against Latest EAP Snapshot causes some errors which might be an issue.

Patch:
```diff
diff --git a/build.gradle b/build.gradle
index 0986fa0..6c9e00c 100644
--- a/build.gradle
+++ b/build.gradle
@@ -30,7 +30,7 @@ sourceSets {
 }

 intellij {
-    version System.getenv().getOrDefault('IDEA_VERSION', ideaVersion)
+    version 'IU-LATEST-EAP-SNAPSHOT'
     type ideaType
     pluginName pluginName
     downloadSources Boolean.valueOf(sources)
```

Error:
```
:compileJava FAILED
C:\...\idea-gitignore\src\mobi\hsz\idea\gitignore\ui\IgnoreSettingsPanel.java:419: error: reference to save is ambiguous
                    ).save(null, null);
                     ^
  both method save(VirtualFile,String) in FileSaverDialog and method save(Path,String) in FileSaverDialog match
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```
